# In elasticsearch node run $bin/elasticsearch-service-tokens create elastic/kibana kibana-kibana
kibanaConfig:
  kibana.yml: |
    elasticsearch.hosts: ["https://elasticsearch-master:9200"]
    elasticsearch.serviceAccountToken: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1raWJhbmE6bWUyMkhWeU9RNVMxcjdReDNxTnlNQQ"
    elasticsearch.ssl.verificationMode: none

extraEnvs:
- name: NODE_TLS_REJECT_UNAUTHORIZED
  value: "0"

ingress:
  enabled: true
  className: "nginx"
  pathtype: ImplementationSpecific
  hosts:
  - host: test-kibana.tss.local
    paths:
    - path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
